# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ""
description: ""
keywords:
author: Ley Z
language: zh-CN
timezone: ""
# Fluid主题配置
# 全局https
force_https: true
# 博客标题
navbar:
  blog_title: Ley的博客
  menu:
    - { key: "首页", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "归档", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "分类", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "标签", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - {
        key: "关于",
        link: "/about/",
        icon: "iconfont icon-user-fill",
        name: "关于我",
      }

web_analytics: # 网页访问统计
  enable: true
  leancloud: # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id: fpWXq1gwK3vsubNx2flUrscl-gzGzoHsz
    app_key: VLiYo6eMXH6Z0FKdnAN8PI6F
    server_url: #https://fpwxq1gw.lc-cn-n1-shared.com
footer: # 统计访问次数
  statistics:
    enable: true
    source: "leancloud" # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次" # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
# 打字机
index:
  slogan:
    enable: true
    text: 困得睁不开眼了~
# 开启文章评论
post:
  comments:
    enable: true
    type: valine
valine:
  app_id: oXIUEO5msHR1ksz86Lo5ZxIK-gzGzoHsz
  app_key: YdvXlNo3FqNblgWfE8CfzdmP
  path: window.location.pathname
  placeholder:
  avatar: "retro"
  meta: ["nick", "mail", "link"]
  requiredFields: []
  pageSize: 10
  lang: "zh-CN"
  highlight: false
  recordIP: false
  serverURLs: ""
  emojiCDN:
  emojiMaps:
  enableQQ: false
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Ley-LY/Ley-LY-Ley-LY.github.io.git
  branch: master
  token: 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
